server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shixun?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema: sql/cms.sql
  jpa:
    hibernate:
      ddl-auto: update  # 如果需要,可以进行自动建表
    show-sql: true  # 如果需要,可以显示执行的sql语句
    properties:
      hibernate:
        format_sql: true  # 如果需要,可以格式化sql语句

  mvc:
    format:
      date: yyyy-MM-dd